/*
 * Copyright (c) 2018 dika.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    dika - initial API and implementation and/or initial documentation
 */
package com.reckitBekinser.activity;

import com.dika.view.component.Frame;
import com.dika.view.component.MenuBar;

import javax.swing.*;

/**
 *
 * @author dika
 */
public class MainViewImpl extends Frame implements MainView {

    /**
     * Creates new form MainViewImpl
     */
    public MainViewImpl() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPaneAdmin = new javax.swing.JTabbedPane();
        sparepartMasukContainer1 = new com.reckitBekinser.activity.main.SparepartMasukContainer();
        sparepartKeluarContainer1 = new com.reckitBekinser.activity.main.SparepartKeluarContainer();
        menuBar = new com.dika.view.component.MenuBar();
        javax.swing.JMenu programMenu = new javax.swing.JMenu();
        changeUsernameMenu = new javax.swing.JMenuItem();
        changePasswordMenu = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator1 = new javax.swing.JPopupMenu.Separator();
        logoutMenu = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();
        dataManagerMenu = new javax.swing.JMenu();
        mdSparepartMenu = new javax.swing.JMenuItem();
        mdSupplierMenu = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mdKaryawanMenu = new javax.swing.JMenuItem();
        mdUserMenu = new javax.swing.JMenuItem();
        javax.swing.JMenu aboutMenu = new javax.swing.JMenu();
        abProgramMenu = new javax.swing.JMenuItem();
        abLaundryMenu = new javax.swing.JMenuItem();
        abUnivMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPaneAdmin.addTab("Sparepart Masuk", sparepartMasukContainer1);
        tabPaneAdmin.addTab("Sparepart Keluar", sparepartKeluarContainer1);

        programMenu.setText("Program");

        changeUsernameMenu.setText("Ganti Username");
        programMenu.add(changeUsernameMenu);

        changePasswordMenu.setText("Ganti Password");
        programMenu.add(changePasswordMenu);
        programMenu.add(jSeparator1);

        logoutMenu.setText("Logout");
        programMenu.add(logoutMenu);

        exitMenu.setText("Keluar");
        programMenu.add(exitMenu);

        menuBar.add(programMenu);

        dataManagerMenu.setText("Data Manager");

        mdSparepartMenu.setText("Manager Data Sparepart");
        dataManagerMenu.add(mdSparepartMenu);

        mdSupplierMenu.setText("Manager Data Supplier");
        dataManagerMenu.add(mdSupplierMenu);
        dataManagerMenu.add(jSeparator2);

        mdKaryawanMenu.setText("Manager Data Karyawan");
        dataManagerMenu.add(mdKaryawanMenu);

        mdUserMenu.setText("Manager Data User");
        dataManagerMenu.add(mdUserMenu);

        menuBar.add(dataManagerMenu);

        aboutMenu.setText("Tentang");

        abProgramMenu.setText("Tentang Program");
        aboutMenu.add(abProgramMenu);

        abLaundryMenu.setText("Tentang Laundry");
        aboutMenu.add(abLaundryMenu);

        abUnivMenu.setText("Tentang Universitas");
        aboutMenu.add(abUnivMenu);

        menuBar.add(aboutMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPaneAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPaneAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abLaundryMenu;
    private javax.swing.JMenuItem abProgramMenu;
    private javax.swing.JMenuItem abUnivMenu;
    private javax.swing.JMenuItem changePasswordMenu;
    private javax.swing.JMenuItem changeUsernameMenu;
    private javax.swing.JMenu dataManagerMenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JMenuItem logoutMenu;
    private javax.swing.JMenuItem mdKaryawanMenu;
    private javax.swing.JMenuItem mdSparepartMenu;
    private javax.swing.JMenuItem mdSupplierMenu;
    private javax.swing.JMenuItem mdUserMenu;
    private com.dika.view.component.MenuBar menuBar;
    private com.reckitBekinser.activity.main.SparepartKeluarContainer sparepartKeluarContainer1;
    private com.reckitBekinser.activity.main.SparepartMasukContainer sparepartMasukContainer1;
    private javax.swing.JTabbedPane tabPaneAdmin;
    // End of variables declaration//GEN-END:variables


    @Override
    public MenuBar getMainMenuBar() {
        return menuBar;
    }

    @Override
    public JTabbedPane getAdmintTabbedPane() {
        return tabPaneAdmin;
    }

    @Override
    public JMenu getDataManagerMenu() {
        return dataManagerMenu;
    }

    @Override
    public JMenuItem getAbLaundryMenu() {
        return abLaundryMenu;
    }

    @Override
    public JMenuItem getAbProgramMenu() {
        return abProgramMenu;
    }

    @Override
    public JMenuItem getAbUnivMenu() {
        return abUnivMenu;
    }

    @Override
    public JMenuItem getChangePasswordMenu() {
        return changePasswordMenu;
    }

    @Override
    public JMenuItem getChangeUsernameMenu() {
        return changeUsernameMenu;
    }

    @Override
    public JMenuItem getExitMenu() {
        return exitMenu;
    }

    @Override
    public JMenuItem getLogoutMenu() {
        return logoutMenu;
    }

    @Override
    public JMenuItem getMdKaryawanMenu() {
        return mdKaryawanMenu;
    }

    @Override
    public JMenuItem getMdUserMenu() {
        return mdUserMenu;
    }

    @Override
    public JMenuItem getMdSparepartMenu() {
        return mdSparepartMenu;
    }

    @Override
    public JMenuItem getMdSupplierMenu() {
        return mdSupplierMenu;
    }

    @Override
    public Frame getRoot() {
        return this;
    }
}
